CREATE TABLE roles (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  isAdmin BIT(1) DEFAULT 0,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
  queryable VARCHAR(255) GENERATED ALWAYS AS (UPPER(CONCAT(name, '|', if(isAdmin > 0, 'true', 'false'), '|', createdOn, '|', updatedOn))),
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  name VARCHAR(16) NOT NULL,
  email VARCHAR(50) NOT NULL,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  roleId INT NOT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  queryable VARCHAR(255) GENERATED ALWAYS AS (UPPER(CONCAT(name, '|', email, '|', firstName, '|', lastName, '|', createdOn, '|', updatedOn))),
  FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (id)
);

CREATE TABLE auth (
  id int NOT NULL AUTO_INCREMENT,
  password VARCHAR(255) NOT NULL,
  expirationDate TIMESTAMP NOT NULL,
  userId INT NOT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (id)
);
